# Datasource (aus 01B, bleibt)
spring.datasource.url=jdbc:postgresql://localhost:5432/quizdb
spring.datasource.username=quizUser
spring.datasource.password=quizPW

# NEU: Hibernate erstellt/aktualisiert die Tabellen anhand deiner Entities
spring.jpa.hibernate.ddl-auto=update

# NEU: zeigt das erzeugte SQL in der Konsole (zum Lernen sehr nützlich)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true